/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Int;

/**
 *
 * @author marce
 */
public class NivelSocial extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NivelSocial.class.getName());

    /**
     * Creates new form NivelSocial
     */
    public NivelSocial() {
        initComponents();
        NivelSocial.setMinimum(1);
        NivelSocial.setMaximum(5);
        NivelSocial.setValue(3); // Valor inicial

        NivelSocial.setMajorTickSpacing(1);
        NivelSocial.setPaintTicks(true);
        NivelSocial.setPaintLabels(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lbSociabilidad = new javax.swing.JLabel();
        NivelSocial = new javax.swing.JSlider();
        Conversación = new javax.swing.JLabel();
        conversacióntx = new javax.swing.JComboBox<>();
        Comunicacion = new javax.swing.JLabel();
        comunicaciontx = new javax.swing.JComboBox<>();
        relacion = new javax.swing.JLabel();
        Detallistatx = new javax.swing.JCheckBox();
        Divertidotx = new javax.swing.JCheckBox();
        comprensivotx = new javax.swing.JCheckBox();
        Tranquilotx = new javax.swing.JCheckBox();
        Espontáneotx = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbSociabilidad.setText("Nivel de sociabilidad");

        NivelSocial.setMaximum(5);
        NivelSocial.setMinimum(1);

        Conversación.setText("¿Cómo sueles iniciar una conversación?");

        conversacióntx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Me resulta fácil", "Depende de la persona", "Prefiero que la otra persona empiece" }));

        Comunicacion.setText("¿Qué tan importante es para ti la comunicación?");

        comunicaciontx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Muy importante", "Importante", "Poco importante" }));

        relacion.setText("¿Cómo te consideras en una relación de amistad o pareja?");

        Detallistatx.setText("Detallista");
        Detallistatx.setToolTipText("");

        Divertidotx.setText("Divertido(a)");
        Divertidotx.addActionListener(this::DivertidotxActionPerformed);

        comprensivotx.setText("Comprensivo(a)");

        Tranquilotx.setText("Tranquilo(a)");

        Espontáneotx.setText("Espontáneo(a)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(lbSociabilidad))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(NivelSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Conversación)
                                .addGap(31, 31, 31)
                                .addComponent(conversacióntx, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Comunicacion)
                                .addGap(18, 18, 18)
                                .addComponent(comunicaciontx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(relacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comprensivotx)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Divertidotx)
                                            .addComponent(Detallistatx))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Tranquilotx)
                                            .addComponent(Espontáneotx))))))))
                .addContainerGap(224, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(lbSociabilidad)
                .addGap(18, 18, 18)
                .addComponent(NivelSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Conversación)
                    .addComponent(conversacióntx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Comunicacion)
                    .addComponent(comunicaciontx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(relacion)
                    .addComponent(Detallistatx)
                    .addComponent(Tranquilotx))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Divertidotx)
                    .addComponent(Espontáneotx))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comprensivotx)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DivertidotxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivertidotxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DivertidotxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NivelSocial().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Comunicacion;
    private javax.swing.JLabel Conversación;
    private javax.swing.JCheckBox Detallistatx;
    private javax.swing.JCheckBox Divertidotx;
    private javax.swing.JCheckBox Espontáneotx;
    private javax.swing.JSlider NivelSocial;
    private javax.swing.JCheckBox Tranquilotx;
    private javax.swing.JCheckBox comprensivotx;
    private javax.swing.JComboBox<String> comunicaciontx;
    private javax.swing.JComboBox<String> conversacióntx;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbSociabilidad;
    private javax.swing.JLabel relacion;
    // End of variables declaration//GEN-END:variables
}
