/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Int;

import java.awt.Color;




/**
 *
 * @author marce
 */
public class Pantalla extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Pantalla.class.getName());

    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();

    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txnombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txapellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txcelular = new javax.swing.JTextField();
        Correopng = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        F1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        passw = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txcorreo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellido:");

        txapellido.addActionListener(this::txapellidoActionPerformed);

        jLabel6.setText("Celular:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Correopng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Int/Imagen/correop.png"))); // NOI18N
        getContentPane().add(Correopng, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, 30, 20));

        jSeparator2.setForeground(new java.awt.Color(69, 30, 105));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, 280, 10));

        jLabel5.setText("Contraseña:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, -1, -1));

        F1.setBackground(new java.awt.Color(69, 30, 105));
        F1.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        F1.setForeground(new java.awt.Color(255, 255, 255));
        F1.setText("Registrate");
        F1.addActionListener(this::F1ActionPerformed);
        getContentPane().add(F1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 580, 110, 40));

        jLabel10.setText("¿No tienes cuenta?");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 560, -1, -1));

        passw.setForeground(new java.awt.Color(204, 204, 204));
        passw.setText("jPasswordField1");
        passw.setBorder(null);
        passw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passwMousePressed(evt);
            }
        });
        getContentPane().add(passw, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, 280, 20));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 3, 24)); // NOI18N
        jLabel1.setText("Tu nuevo perfil");
        jLabel1.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, 190, 40));

        jButton1.setText("Iniciar sesión");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 450, 110, 40));

        jSeparator1.setForeground(new java.awt.Color(69, 30, 105));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 410, 280, 10));

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        jLabel9.setText("INICIAR SESION");
        jLabel9.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, 290, 40));

        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 280, -1, -1));

        txcorreo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 2, 14)); // NOI18N
        txcorreo.setForeground(new java.awt.Color(204, 204, 204));
        txcorreo.setText("Ingrese su correo");
        txcorreo.setToolTipText("");
        txcorreo.setBorder(null);
        txcorreo.setCaretColor(new java.awt.Color(255, 255, 255));
        txcorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txcorreoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txcorreoMousePressed(evt);
            }
        });
        txcorreo.addActionListener(this::txcorreoActionPerformed);
        getContentPane().add(txcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 310, 215, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Int/Imagen/sin bordes.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Int/Imagen/Sin título.jpg"))); // NOI18N
        jLabel7.setToolTipText("");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1357, 739));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void F1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F1ActionPerformed

        F2 Registro = new F2();
        Registro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_F1ActionPerformed

    private void txcorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txcorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txcorreoActionPerformed

    private void txapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txapellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txapellidoActionPerformed

    private void txcorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txcorreoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txcorreoMouseClicked

    private void txcorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txcorreoMousePressed
        txcorreo.setText("");
        txcorreo.setForeground(Color.black);
        passw.setText("********");
        passw.setForeground(Color.gray);
    }//GEN-LAST:event_txcorreoMousePressed

    private void passwMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwMousePressed
        txcorreo.setText("Ingrese su correo");
        txcorreo.setForeground(Color.gray);
        passw.setText("");
        passw.setForeground(Color.black);
    }//GEN-LAST:event_passwMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Pantalla().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Correopng;
    private javax.swing.JButton F1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField passw;
    private javax.swing.JTextField txapellido;
    private javax.swing.JTextField txcelular;
    private javax.swing.JTextField txcorreo;
    private javax.swing.JTextField txnombre;
    // End of variables declaration//GEN-END:variables
}
