/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Int;

/**
 *
 * @author marce
 */
public class PerfilUsuario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PerfilUsuario.class.getName());

    /**
     * Creates new form PerfilUsuario
     */
    public PerfilUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sobreti = new javax.swing.JLabel();
        edad = new javax.swing.JLabel();
        edadtx = new javax.swing.JTextField();
        género = new javax.swing.JLabel();
        génerotx = new javax.swing.JTextField();
        Ubicación = new javax.swing.JLabel();
        Ubicacióntx = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sobreti.setText("Sobre ti");
        jPanel1.add(sobreti, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 50, 20));

        edad.setText("Edad");
        jPanel1.add(edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        edadtx.setText("jTextField1");
        jPanel1.add(edadtx, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        género.setText("Género");
        jPanel1.add(género, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        génerotx.setText("jTextField1");
        génerotx.addActionListener(this::génerotxActionPerformed);
        jPanel1.add(génerotx, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        Ubicación.setText("Ubicación");
        jPanel1.add(Ubicación, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        Ubicacióntx.setText("jTextField1");
        Ubicacióntx.addActionListener(this::UbicacióntxActionPerformed);
        jPanel1.add(Ubicacióntx, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(285, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void génerotxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_génerotxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_génerotxActionPerformed

    private void UbicacióntxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbicacióntxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UbicacióntxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PerfilUsuario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ubicación;
    private javax.swing.JTextField Ubicacióntx;
    private javax.swing.JLabel edad;
    private javax.swing.JTextField edadtx;
    private javax.swing.JLabel género;
    private javax.swing.JTextField génerotx;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel sobreti;
    // End of variables declaration//GEN-END:variables
}
