/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Int;

/**
 *
 * @author marce
 */
public class PerfilUsuario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PerfilUsuario.class.getName());

    /**
     * Creates new form PerfilUsuario
     */
    public PerfilUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sobreti = new javax.swing.JLabel();
        edad = new javax.swing.JLabel();
        edadtx = new javax.swing.JTextField();
        género = new javax.swing.JLabel();
        génerotx = new javax.swing.JTextField();
        Altura = new javax.swing.JLabel();
        alturatx = new javax.swing.JTextField();
        Ubicación1 = new javax.swing.JLabel();
        Ubicacióntx = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        pesotx = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        discapacidadtx = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sobreti.setText("Sobre ti");
        jPanel1.add(sobreti, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 50, 20));

        edad.setText("Edad");
        jPanel1.add(edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        edadtx.setText("jTextField1");
        jPanel1.add(edadtx, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        género.setText("Género");
        jPanel1.add(género, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        génerotx.setText("jTextField1");
        génerotx.addActionListener(this::génerotxActionPerformed);
        jPanel1.add(génerotx, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        Altura.setText("Altura");
        jPanel1.add(Altura, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        alturatx.setText("jTextField1");
        alturatx.addActionListener(this::alturatxActionPerformed);
        jPanel1.add(alturatx, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));

        Ubicación1.setText("Ubicación");
        jPanel1.add(Ubicación1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        Ubicacióntx.setText("jTextField1");
        Ubicacióntx.addActionListener(this::UbicacióntxActionPerformed);
        jPanel1.add(Ubicacióntx, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        jLabel1.setText("Peso");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 40, 20));

        pesotx.setText("jTextField1");
        pesotx.addActionListener(this::pesotxActionPerformed);
        jPanel1.add(pesotx, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, -1, -1));

        jLabel2.setText("Discapacidad");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        discapacidadtx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
        discapacidadtx.addActionListener(this::discapacidadtxActionPerformed);
        jPanel1.add(discapacidadtx, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 70, 30));

        jLabel3.setText("Situación laboral");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solo estudio", "Estudio y trabajo", "Trabajo a tiempo completo", "Trabajo a medio tiempo" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 110, -1));

        jLabel4.setText("Estado civil");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soltero", "Casado", "Divorciado" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, -1, -1));

        jLabel5.setText("¿Tiene hijos?");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
        jPanel1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, -1, -1));

        jLabel6.setText("Carrera");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, -1, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void discapacidadtxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discapacidadtxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discapacidadtxActionPerformed

    private void pesotxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesotxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesotxActionPerformed

    private void UbicacióntxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbicacióntxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UbicacióntxActionPerformed

    private void alturatxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alturatxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alturatxActionPerformed

    private void génerotxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_génerotxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_génerotxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PerfilUsuario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Altura;
    private javax.swing.JLabel Ubicación1;
    private javax.swing.JTextField Ubicacióntx;
    private javax.swing.JTextField alturatx;
    private javax.swing.JComboBox<String> discapacidadtx;
    private javax.swing.JLabel edad;
    private javax.swing.JTextField edadtx;
    private javax.swing.JLabel género;
    private javax.swing.JTextField génerotx;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField pesotx;
    private javax.swing.JLabel sobreti;
    // End of variables declaration//GEN-END:variables
}
