/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Int;

/**
 *
 * @author marce
 */
public class ReferenciaSexual extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReferenciaSexual.class.getName());

    /**
     * Creates new form ReferenciaSexual
     */
    public ReferenciaSexual() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tiporelacion = new javax.swing.JLabel();
        tiporelaciontx = new javax.swing.JComboBox<>();
        edadpref = new javax.swing.JLabel();
        edadpreftx = new javax.swing.JSlider();
        PreferenciaPersonalidad = new javax.swing.JPanel();
        PrefPersonalidadtx = new javax.swing.JComboBox<>();
        preferenciasFísicas = new javax.swing.JPanel();
        complex = new javax.swing.JLabel();
        estaturatx = new javax.swing.JComboBox<>();
        estatura = new javax.swing.JLabel();
        complextx = new javax.swing.JComboBox<>();
        buscarRelacion = new javax.swing.JPanel();
        buscarrelaciontx = new javax.swing.JComboBox<>();
        Géneroideal = new javax.swing.JPanel();
        noespecificartx = new javax.swing.JCheckBox();
        hombretx = new javax.swing.JCheckBox();
        mujertx = new javax.swing.JCheckBox();
        ambostx = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tiporelacion.setText("Tipo de relación");
        jPanel1.add(tiporelacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        tiporelaciontx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seria", "Casual", "Amistad", "Sin compromiso", "Indefinido" }));
        tiporelaciontx.addActionListener(this::tiporelaciontxActionPerformed);
        jPanel1.add(tiporelaciontx, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 70, -1));

        edadpref.setText("Rango de edad preferido");
        jPanel1.add(edadpref, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));
        jPanel1.add(edadpreftx, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        PreferenciaPersonalidad.setBorder(javax.swing.BorderFactory.createTitledBorder("Preferencia de personalidad"));
        PreferenciaPersonalidad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PrefPersonalidadtx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Extrovertido / Introvertido", "Divertido / Serio", "Cariñoso / Reservado", "Ambicioso / Relajado" }));
        PreferenciaPersonalidad.add(PrefPersonalidadtx, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 180, -1));

        jPanel1.add(PreferenciaPersonalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 200, 50));

        preferenciasFísicas.setBorder(javax.swing.BorderFactory.createTitledBorder("Preferencias Físicas"));
        preferenciasFísicas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        complex.setText("Complexión");
        preferenciasFísicas.add(complex, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        estaturatx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alto", "Bajo", "Misma estatura" }));
        preferenciasFísicas.add(estaturatx, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 70, -1));

        estatura.setText("Estatura ideal");
        preferenciasFísicas.add(estatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        complextx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Delgado/a", "Atlético/a", "Normal", "Robusto/a" }));
        preferenciasFísicas.add(complextx, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        jPanel1.add(preferenciasFísicas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 240, 120));

        buscarRelacion.setBorder(javax.swing.BorderFactory.createTitledBorder("Describe que buscas en una relación"));
        buscarRelacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buscarrelaciontx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Extrovertido / Introvertido", "Divertido / Serio", "Cariñoso / Reservado", "Ambicioso / Relajado" }));
        buscarRelacion.add(buscarrelaciontx, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 180, -1));

        jPanel1.add(buscarRelacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 290, 50));

        Géneroideal.setBorder(javax.swing.BorderFactory.createTitledBorder("Género de preferencia"));
        Géneroideal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        noespecificartx.setText("No especificar");
        Géneroideal.add(noespecificartx, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        hombretx.setText("Hombre");
        Géneroideal.add(hombretx, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        mujertx.setText("Mujer");
        Géneroideal.add(mujertx, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        ambostx.setText("Ambos");
        Géneroideal.add(ambostx, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jPanel1.add(Géneroideal, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 150, 120));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tiporelaciontxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiporelaciontxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiporelaciontxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReferenciaSexual().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Géneroideal;
    private javax.swing.JComboBox<String> PrefPersonalidadtx;
    private javax.swing.JPanel PreferenciaPersonalidad;
    private javax.swing.JCheckBox ambostx;
    private javax.swing.JPanel buscarRelacion;
    private javax.swing.JComboBox<String> buscarrelaciontx;
    private javax.swing.JLabel complex;
    private javax.swing.JComboBox<String> complextx;
    private javax.swing.JLabel edadpref;
    private javax.swing.JSlider edadpreftx;
    private javax.swing.JLabel estatura;
    private javax.swing.JComboBox<String> estaturatx;
    private javax.swing.JCheckBox hombretx;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox mujertx;
    private javax.swing.JCheckBox noespecificartx;
    private javax.swing.JPanel preferenciasFísicas;
    private javax.swing.JLabel tiporelacion;
    private javax.swing.JComboBox<String> tiporelaciontx;
    // End of variables declaration//GEN-END:variables
}
