/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Int;

/**
 *
 * @author marce
 */
public class Registrar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Registrar.class.getName());

    /**
     * Creates new form F2
     */
    public Registrar(){
    initComponents();
}
    public Registrar(String nombre, String apellido, String correo, String celular) {
        
        initComponents();
        
        txnombre.setText(nombre);
        txapellido.setText(apellido);
        txcorreo.setText(correo);
        
        txcelular.setText(celular);
        
        txnombre.setEditable(false);
        txapellido.setEditable(false);
        txcorreo.setEditable(false);
        txcelular.setEditable(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txnombre = new javax.swing.JTextField();
        txapellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txcorreo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txpss = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txcelular = new javax.swing.JTextField();
        F1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("REGISTRO DE USUARIO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, 71));

        txnombre.setEditable(false);
        jPanel1.add(txnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 105, 215, -1));

        txapellido.setEditable(false);
        jPanel1.add(txapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 201, 215, -1));

        jLabel3.setText("Apellido:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 179, -1, -1));

        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 83, -1, -1));

        txcorreo.setEditable(false);
        jPanel1.add(txcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 297, 215, -1));

        jLabel4.setText("Correo:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 275, -1, -1));

        txpss.setEditable(false);
        jPanel1.add(txpss, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 393, 215, -1));

        jLabel5.setText("Contraseña:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 371, -1, -1));

        jLabel6.setText("Celular:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 467, 63, -1));

        txcelular.setEditable(false);
        jPanel1.add(txcelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 489, 215, -1));

        F1.setText("¡Listo!");
        F1.addActionListener(this::F1ActionPerformed);
        jPanel1.add(F1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 540, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void F1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F1ActionPerformed
        String nombre = txnombre.getText();
        String apellido = txapellido.getText();
        String correo = txcorreo.getText();
        
        String celular = txcelular.getText();
    }//GEN-LAST:event_F1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Registrar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton F1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txapellido;
    private javax.swing.JTextField txcelular;
    private javax.swing.JTextField txcorreo;
    private javax.swing.JTextField txnombre;
    private javax.swing.JTextField txpss;
    // End of variables declaration//GEN-END:variables
}
